"""New Migration

Revision ID: c60c4ebad9ae
Revises: 
Create Date: 2024-01-14 17:30:32.451329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60c4ebad9ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('img_base64', sa.String(), nullable=True),
    sa.Column('malade', sa.Boolean(), nullable=True),
    sa.Column('precision', sa.String(), nullable=True),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('gravite', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_base64', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('analyses')
    # ### end Alembic commands ###
